version: '2'

services:
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    restart: unless-stopped
    environment:
      - PUID=65534
      - PGID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=65534
      - PGID=65534
      - TZ='America/Los Angeles'
    ports:
      - 6767:6767
    volumes:
      - /opt/gnas/bazarr:/config
      - /storage/Movies:/movies
      - /storage/TV:/tv

  hydra2:
    container_name: hydra2
    image: linuxserver/hydra2:latest
    restart: unless-stopped
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 5076:5076/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/hydra2:/config
      - /storage/Downloads:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PGID=65534
      - PUID=65534
    ports:
      - 9117:9117/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/jackett:/config
      - /storage/Downloads/complete:/downloads

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8686:8686/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/lidarr:/config
      - /storage/Downloads/complete/audio:/downloads
      - /storage/Audio:/music

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 6789:6789/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/nzbget:/config
      - /storage/Downloads:/downloads


  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - PLEX_GID=65534
      - PLEX_UID=65534
      - TZ='America/Los Angeles'
    network_mode: host
    volumes:
      - /opt/gnas/plex:/config
      - /storage:/data
      - /storage/Transcode:/transcode

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PGID=65534
      - PUID=65534
      - UMASK_SET=022
      - TZ='America/Los Angeles'
      - WEBUI_PORT=8181
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8181:8181
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/qbittorrent:/config
      - /storage/Downloads:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 7878:7878/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/radarr:/config
      - /storage/Downloads/complete/movies:/downloads
      - /storage/Movies:/movies

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8989:8989/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/sonarr:/config
      - /storage/Downloads/complete/tv:/downloads
      - /storage/TV:/tv
