version: '3'

services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    environment:
      - PGID=65534
      - PUID=65534
    networks:
      - default
    ports:
      - 9117:9117/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/jackett:/config

  hydra2:
    container_name: hydra2
    image: linuxserver/hydra2:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 5076:5076/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/hydra2:/config
      - /storage/Downloads:/downloads

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 8080:8080/tcp
      - 9090:9090/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/sabnzbd:/config
      - /storage/Downloads:/downloads

  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 9091:8091
      - 51413:51413/tcp
      - 51413:51413/udp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/transmission:/config
      - /storage/Downloads/complete:/downloads
      - /storage/Downloads/incomplete/transmission:/incomplete
      - /storage/Downloads/watched:/watch

  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 5050:5050/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/couchpotato:/config
      - /storage/Downloads:/downloads
      - /storage/Movies:/movies

  sickgear:
    environment:
      - PGID=65534
      - PUID=65534
    container_name: sickgear
    image: linuxserver/sickgear:latest
    networks:
      - default
    ports:
      - 8989:8989/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/sickgear:/config
      - /storage/Downloads:/downloads
      - /storage/TV:/tv

  headphones:
    container_name: headphones
    image: linuxserver/headphones:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 8686:8686/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/headphones:/config
      - /storage/Downloads:/downloads
      - /storage/Music:/music

  tvheadend:
    container_name: tvheadend
    image: linuxserver/tvheadend:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 9881:9881/tcp
      - 9882:9882/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/tvheadend:/config
      - /storage/DVR:/recordings

  kodi_headless:
    container_name: kodi_headless
    image: linuxserver/kodi-headless:latest
    depends_on:
      - mysql
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 8080:8181/tcp
      - 9090:9191/tcp
      - 9777:9777/udp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/kodi_headless:/config/.kodi

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
      - MYSQL_ROOT_PASSWORD=SomethingSecure123!
    networks:
      - default
    ports:
      - 3306:3306/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/mysql:/config

  openvpn_as:
    container_name: openvpn_as
    image: linuxserver/openvpn-as:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
      - INTERFACE=eth0
    networks:
      - default
    ports:
      - 1194:1194/udp
    privileged: true
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/openvpn_as:/config

networks:
  default:
    driver: bridge
