version: '2'

services:
  cardigann:
    container_name: cardigann
    image: linuxserver/cardigann:latest
    environment:
      - PGID=65534
      - PUID=65534
    networks:
      - backend
    ports:
      - 5060:5060/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/cardigann:/config

  nzbhydra:
    container_name: nzbhydra
    image: linuxserver/hydra:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - backend
    ports:
      - 5075:5075/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/nzbhydra:/config
      - /storage/Downloads:/downloads

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - backend
    ports:
      - 8080:8080/tcp
      - 9090:9090/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/sabnzbd:/config
      - /storage/Downloads:/downloads

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK_SET=022
      - TZ='America/Los Angeles'
    networks:
      - backend
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946
      - 58946:58946/udp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/deluge:/config
      - /storage/Downloads:/downloads

  couchpotato:
    container_name: radarr
    image: linuxserver/couchpotato:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - backend
    ports:
      - 5050:5050/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/couchpotato:/config
      - /storage/Downloads:/downloads
      - /storage/Movies:/movies

  sonarr:
    environment:
      - PGID=65534
      - PUID=65534
    container_name: sonarr
    image: linuxserver/sonarr:latest
    networks:
      - backend
    ports:
      - 8989:8989/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /dev/rtc:/dev/rtc:ro
      - /opt/gnas/sonarr:/config
      - /storage/Downloads:/downloads
      - /storage/TV:/tv

  headphones:
    container_name: lidarr
    image: linuxserver/headphones:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - backend
    ports:
      - 8282:8181/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/headphones:/config
      - /storage/Downloads:/downloads
      - /storage:/music

  tvheadend:
    container_name: tvheadend
    image: linuxserver/tvheadend:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - backend
    ports:
      - 9881:9881/tcp
      - 9882:9882/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/tvheadend:/config
      - /storage/DVR:/recordings

  kodi_headless:
    container_name: kodi_headless
    image: linuxserver/kodi-headless:latest
    depends_on:
      - mysql
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - backend
    ports:
      - 8181:8181/tcp
      - 9777:9777/udp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/kodi_headless:/config/.kodi

  mysql:
    container_name: mysql
    image: linuxserver/mysql:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
      - MYSQL_ROOT_PASSWORD=SomethingSecure123!
    networks:
      - backend
    ports:
      - 3306:3306/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/mysql:/config

  openvpn_as:
    container_name: openvpn_as
    image: linuxserver/openvpn-as:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
      - INTERFACE=eth0
    networks:
      - backend
    ports:
      - 1194:1194/udp
    privileged: true
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/openvpn_as:/config

networks:
  backend:
    driver: bridge
