version: '2'

services:
  app:
    command: [
      "--templates",
      "https://raw.githubusercontent.com/gtrummell/gnas-portainer-templates/master/templates.json"
    ]
    container_name: portainer-app
    image: portainer/portainer:latest
    ports:
      - 9000:9000/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/portainer:/data
