version: '2'

services:
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    restart: on-failure
    environment:
      - PUID=65534
      - PGID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  prometheus:
    container_name: prometheus
    image: linuxserver/bazarr:latest
    restart: on-failure
    environment:
      - PUID=65534
      - PGID=65534
      - TZ='America/Los Angeles'
    ports:
      - 6767:6767
    volumes:
      - /opt/gnas/bazarr:/config
      - /storage/Movies:/movies
      - /storage/TV:/tv

  alertmanager:
    container_name: alertmanager
    image: linuxserver/hydra2:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 5076:5076/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/hydra2:/config

  pushgateway:
    container_name: pushgateway
    image: linuxserver/jackett:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
    ports:
      - 9117:9117/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/jackett:/config
      - /storage/Downloads/complete:/downloads

  grafana:
    container_name: grafana
    image: linuxserver/jellyfin:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/jellyfin/config:/config
      - /opt/gnas/jellyfin/plugins:/var/lib/jellyfin/plugins
      - /storage:/data
      - /storage/Transcode:/transcode

  sabnzbd_exporter:
    container_name: sabnzbd_exporter
    image: msroest/sabnzbd_exporter:latest
    restart: on-failure
    environment:
      - SABNZBD_BASEURL=http://gnas:8088/sabnzbd
      - SABNZBD_APIKEY=<apikey>
    ports:
      - 9387:9387/tcp

  transmission_exporter:
    container_name: transmission_exporter
    image: metalmatze/transmission-exporter:latest
    restart: on-failure
    environment:
      - WEB_ADDR=:19091
      - TRANSMISSION_ADDR=http://gnas:9099
      #- TRANSMISSION_USERNAME= <uncomment and fill in with a username>
      #- TRANSMISSION_PASSWORD= <uncomment and fill in with a password>
    ports:
      - 19091:19091/tcp
