version: '2'

services:
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: on-failure
    environment:
      - PUID=65534
      - PGID=65534
      - TZ='America/Los Angeles'
    ports:
      - 6767:6767
    volumes:
      - /opt/gnas/bazarr:/config
      - /storage/Movies:/movies
      - /storage/TV:/tv

  hydra2:
    container_name: hydra2
    image: linuxserver/hydra2:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 5076:5076/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/hydra2:/config
      - /storage/Downloads/complete:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
    ports:
      - 9117:9117/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/jackett:/config
      - /storage/Downloads/complete:/downloads

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/jellyfin/config:/config
      - /opt/gnas/jellyfin/plugins:/var/lib/jellyfin/plugins
      - /storage:/data
      - /storage/Transcode:/transcode

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8686:8686/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/lidarr:/config
      - /storage/Downloads/complete/audio:/downloads
      - /storage/Audio:/music

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 6789:6789/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/nzbget:/config
      - /storage/Downloads/complete:/downloads
      - /storage/Downloads/incomplete/nzbget:/incomplete-downloads
      - /storage/Downloads/watched/nzbget:/watch

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: on-failure
    environment:
      - PLEX_GID=65534
      - PLEX_UID=65534
      - TZ='America/Los Angeles'
    network_mode: host
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/plex:/config
      - /storage:/data
      - /storage/Transcode:/transcode

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - UMASK_SET=022
      - TZ='America/Los Angeles'
      - WEBUI_PORT=8181
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8181:8181
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/qbittorrent:/config
      - /storage/Downloads/complete:/downloads
      - /storage/Downloads/incomplete/qbittorrent:/incomplete-downloads
      - /storage/Downloads/watched/qbittorrent:/watch

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 7878:7878/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/radarr:/config
      - /storage/Downloads/complete/movies:/downloads
      - /storage/Movies:/movies

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8989:8989/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/sonarr:/config
      - /storage/Downloads/complete/tv:/downloads
      - /storage/TV:/tv
