version: '2'

services:
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: on-failure
    environment:
      - PUID=65534
      - PGID=65534
      - TZ='America/Los Angeles'
    ports:
      - 6767:6767
    volumes:
      - /opt/gnas/bazarr:/config
      - /storage/Movies:/movies
      - /storage/TV:/tv

  hydra2:
    container_name: hydra2
    image: linuxserver/hydra2:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 5076:5076/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/hydra2:/config
      - /storage/Downloads:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
    ports:
      - 9117:9117/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/jackett:/config
      - /storage/Downloads/complete:/downloads

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/jellyfin/config:/config
      - /opt/gnas/jellyfin/plugins:/var/lib/jellyfin/plugins
      - /storage:/data
      - /storage/Transcode:/transcode

  kodi_headless:
    container_name: kodi_headless
    image: linuxserver/kodi-headless:latest
    depends_on:
      - mysql
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 8181:8080/tcp
      - 9191:9090/tcp
      - 9777:9777/udp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/kodi_headless:/config/.kodi

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8686:8686/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/lidarr:/config
      - /storage/Downloads/complete/audio:/downloads
      - /storage/Audio:/music

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
      - MYSQL_ROOT_PASSWORD=SomethingSecure123!
    networks:
      - default
    ports:
      - 3306:3306/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/mysql:/config

  openvpn_as:
    container_name: openvpn_as
    image: linuxserver/openvpn-as:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
      - INTERFACE=eth0
    networks:
      - default
    ports:
      - 1194:1194/udp
    privileged: true
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/openvpn_as:/config

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: on-failure
    environment:
      - PLEX_GID=65534
      - PLEX_UID=65534
      - TZ='America/Los Angeles'
    network_mode: host
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/plex:/config
      - /storage:/data
      - /storage/Transcode:/transcode

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 7878:7878/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/radarr:/config
      - /storage/Downloads/complete/movies:/downloads
      - /storage/Movies:/movies

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 8088:8080/tcp
      - 8099:9090/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/sabnzbd:/config
      - /storage/Downloads/complete:/downloads
      - /storage/Downloads/incomplete/sabnzbd:/incomplete

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: on-failure
    environment:
      - PGID=65534
      - PUID=65534
      - TZ='America/Los Angeles'
    ports:
      - 8989:8989/tcp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/sonarr:/config
      - /storage/Downloads/complete/tv:/downloads
      - /storage/TV:/tv

  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - TZ='America/Los Angeles'
    networks:
      - default
    ports:
      - 8901:9091
      - 51413:51413/tcp
      - 51413:51413/udp
    volumes:
      - /opt/gnas/certs:/certs:ro
      - /opt/gnas/transmission:/config
      - /storage/Downloads/complete:/downloads
      - /storage/Downloads/incomplete/transmission:/incomplete
      - /storage/Downloads/watched:/watch

  sabnzbd_exporter:
    container_name: sabnzbd_exporter
    image: msroest/sabnzbd_exporter:latest
    restart: on-failure
    environment:
      - SABNZBD_BASEURL=http://gnas:8088/sabnzbd
      - SABNZBD_APIKEY=<apikey>
    ports:
      - 9387:9387/tcp

  transmission_exporter:
    container_name: transmission_exporter
    image: metalmatze/transmission-exporter:latest
    restart: on-failure
    environment:
      - WEB_ADDR=:19091
      - TRANSMISSION_ADDR=http://gnas:8901
